author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - templates
  - samples
  - openaf
  - ojob
bugs:
  url: 'https://github.com/OpenAF/openaf-templates/issues'
repository:
  type: http
  url: 'https://openaf.io/opacks/OpenAF-templates.opack'
description: OpenAF and oJob templates for faster scripting and job creation.
name: OpenAF-templates
main: ''
mainJob: ''
license: 'https://github.com/OpenAF/openaf-templates/blob/master/LICENSE'
version: '20190906'
dependencies:
  OpenAF: '>=20181001'
  oJob-common: '>=20190302'
files:
  - .package.yaml
  - docker/genDockerFiles4OJobC.yaml
  - docker/nAttrMon/config/outputs/02.httpjson.yaml
  - docker/nAttrMon/config/outputs/03.http.yaml
  - docker/nAttrMon/config/outputs/09.channels.yaml
  - docker/nAttrMon/config/outputs/move_files_from_outputs_disabled.dummy
  - docker/nAttrMon/Dockerfile
  - docker/nAttrMon/main.js
  - docker/README.md
  - LICENSE
  - ojobs/git/copy4GIT.yaml
  - ojobs/httpd/httpd.yaml
  - ojobs/restServices/restServices.yaml
  - ojobs/restServices/restServicesLoggingToES.yaml
  - ojobs/tests/autoTest.js
  - ojobs/tests/autoTest.yaml
  - ojobs/watchdog/watchdog.yaml
  - ojobs/watchdog/watchDogBarkAndLogToES.yaml
  - ojobs/watchdog/watchDogBarkOnSlack.yaml
  - README.md
filesHash:
  docker/genDockerFiles4OJobC.yaml: eaa4072b7d39c79ea6eaa0e8352093967c002d8c
  docker/nAttrMon/config/outputs/02.httpjson.yaml: 6d14637f7fff15b4d75481597bb9ae4f77f12665
  docker/nAttrMon/config/outputs/03.http.yaml: 9c9fc35e949327723dd0efbc8c0eacb068f487cf
  docker/nAttrMon/config/outputs/09.channels.yaml: f38c539f163ec3457267c55d4248237b76caee14
  docker/nAttrMon/config/outputs/move_files_from_outputs_disabled.dummy: b858cb282617fb0956d960215c8e84d1ccf909c6
  docker/nAttrMon/Dockerfile: 6964062316170b5e60c6850d367e2c1350dde93f
  docker/nAttrMon/main.js: d251651ce0accf3c2ff5a00d434e2509d2d593e5
  docker/README.md: 0e944cfc09f81bccc2eb8952b1595b581402870d
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  ojobs/git/copy4GIT.yaml: a1533413e490b0c604b4b95523d977aa4e6ae26a
  ojobs/httpd/httpd.yaml: 7b417c1e2d041bc641a9a96954a31c224b90ae1e
  ojobs/restServices/restServices.yaml: cb83f18818312bd39e9ed56bd1a24c778aebff5c
  ojobs/restServices/restServicesLoggingToES.yaml: d76e6386d50b6b4e301f9740aed483deb986bb39
  ojobs/tests/autoTest.js: 546b8649ba2e9007d1ed252015a1586987db59de
  ojobs/tests/autoTest.yaml: a0b9e836db783e1c26a276e8357e5412348df160
  ojobs/watchdog/watchdog.yaml: ff18fb17ae2a9597928b95a15fdeb21b40d2bfd2
  ojobs/watchdog/watchDogBarkAndLogToES.yaml: 34dd0ab18898ad665b414e11ddd211c251c41ea8
  ojobs/watchdog/watchDogBarkOnSlack.yaml: edc7ce28bd7889f32e612d42e1208d5b3ce605f4
  README.md: d8aa3c1b0addb77929f3c430df6d3297d962499a
