author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - templates
  - samples
  - openaf
  - ojob
bugs:
  url: 'https://github.com/OpenAF/openaf-templates/issues'
repository:
  type: http
  url: 'https://openaf.io/opacks/OpenAF-templates.opack'
description: OpenAF and oJob templates for faster scripting and job creation.
name: OpenAF-templates
main: ''
mainJob: ''
license: 'https://github.com/OpenAF/openaf-templates/blob/master/LICENSE'
version: '20181220'
dependencies:
  OpenAF: '>=20180823'
files:
  - docker/openaf-console/Dockerfile
  - docker/oJob/Dockerfile
  - docker/oJob/main.yaml
  - docker/oJobC/Dockerfile
  - docker/oJobC/main.yaml
  - docker/openaf/Dockerfile
  - docker/genDockerFiles4OJobC.yaml
  - .package.yaml
  - LICENSE
  - README.md
  - ojobs/watchdog/watchDogBarkOnSlack.yaml
  - ojobs/watchdog/watchdog.yaml
  - ojobs/watchdog/watchDogBarkAndLogToES.yaml
  - ojobs/restServices/restServices.yaml
  - ojobs/restServices/restServicesLoggingToES.yaml
filesHash:
  docker/openaf-console/Dockerfile: 8297edb6377ab020d321584290752d89634d57cc
  docker/oJob/Dockerfile: d58e0f851770990b5e195f86dd65d472adf86af1
  docker/oJob/main.yaml: d806e47bd23abb2bdcb105bfcdc78a498bb21792
  docker/oJobC/Dockerfile: 2d485dad9e06f1bd80158689693156f3db2ccd75
  docker/oJobC/main.yaml: d806e47bd23abb2bdcb105bfcdc78a498bb21792
  docker/openaf/Dockerfile: d1083c17dae1d6e7f5e23732ebba3576ca8e3c61
  docker/genDockerFiles4OJobC.yaml: 630f7b2a512d903adab611005487335b91ec4b5b
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 3449ca88cb7177ffcd5eeb4c3a17b35cdc63a40e
  ojobs/watchdog/watchDogBarkOnSlack.yaml: 35181c1db79a164fa3086947fc5f053656b90449
  ojobs/watchdog/watchdog.yaml: 2a29b0cfa020345da589e4e132176a5a5e4db267
  ojobs/watchdog/watchDogBarkAndLogToES.yaml: 877e2aaf8173f026620ef4d20146f5b3b82f2a8c
  ojobs/restServices/restServices.yaml: be18c01edbb6b421752b91f4832ea84280ca4361
  ojobs/restServices/restServicesLoggingToES.yaml: 1b92c8b708f7fb2ab9ed9fc97525de81536da697
