author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - templates
  - samples
  - openaf
  - ojob
bugs:
  url: 'https://github.com/OpenAF/openaf-templates/issues'
repository:
  type: http
  url: 'https://openaf.io/opacks/OpenAF-templates.opack'
description: OpenAF and oJob templates for faster scripting and job creation.
name: OpenAF-templates
main: ''
mainJob: ''
license: 'https://github.com/OpenAF/openaf-templates/blob/master/LICENSE'
version: '20190210'
dependencies:
  OpenAF: '>=20181001'
files:
  - docker/README.md
  - docker/genDockerFiles4OJobC.yaml
  - docker/nAttrMon/config/outputs/03.http.yaml
  - docker/nAttrMon/config/outputs/move_files_from_outputs_disabled.dummy
  - docker/nAttrMon/config/outputs/09.channels.yaml
  - docker/nAttrMon/config/outputs/02.httpjson.yaml
  - docker/nAttrMon/Dockerfile
  - docker/nAttrMon/main.js
  - LICENSE
  - .package.yaml
  - README.md
  - ojobs/watchdog/watchDogBarkOnSlack.yaml
  - ojobs/watchdog/watchdog.yaml
  - ojobs/watchdog/watchDogBarkAndLogToES.yaml
  - ojobs/httpd/httpd.yaml
  - ojobs/git/copy4GIT.yaml
  - ojobs/restServices/restServices.yaml
  - ojobs/restServices/restServicesLoggingToES.yaml
filesHash:
  docker/README.md: 0e944cfc09f81bccc2eb8952b1595b581402870d
  docker/genDockerFiles4OJobC.yaml: eaa4072b7d39c79ea6eaa0e8352093967c002d8c
  docker/nAttrMon/config/outputs/03.http.yaml: 9c9fc35e949327723dd0efbc8c0eacb068f487cf
  docker/nAttrMon/config/outputs/move_files_from_outputs_disabled.dummy: b858cb282617fb0956d960215c8e84d1ccf909c6
  docker/nAttrMon/config/outputs/09.channels.yaml: f38c539f163ec3457267c55d4248237b76caee14
  docker/nAttrMon/config/outputs/02.httpjson.yaml: 6d14637f7fff15b4d75481597bb9ae4f77f12665
  docker/nAttrMon/Dockerfile: 6964062316170b5e60c6850d367e2c1350dde93f
  docker/nAttrMon/main.js: d251651ce0accf3c2ff5a00d434e2509d2d593e5
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 85a9ae8f9440eaadaca0f82c6f6b5f8721275851
  ojobs/watchdog/watchDogBarkOnSlack.yaml: edc7ce28bd7889f32e612d42e1208d5b3ce605f4
  ojobs/watchdog/watchdog.yaml: ff18fb17ae2a9597928b95a15fdeb21b40d2bfd2
  ojobs/watchdog/watchDogBarkAndLogToES.yaml: 34dd0ab18898ad665b414e11ddd211c251c41ea8
  ojobs/httpd/httpd.yaml: 21a625bdcfa394cd7e8912f5110687178cad9dcc
  ojobs/git/copy4GIT.yaml: a1533413e490b0c604b4b95523d977aa4e6ae26a
  ojobs/restServices/restServices.yaml: dde947671a74f3aa245daf59eef6ba87885716c9
  ojobs/restServices/restServicesLoggingToES.yaml: c0c119db077951cdc230c8bc3483c416047785fa
