# Template          : Simple HTTP server
# Author            : Nuno Aguiar
# How to run        : ojob httpd.yaml
# oPack dependencies: latest ojob-common;

consts:
  # The port where the http server will be available
  port  : &PORT   8080
  # Where the pid file will be located
  piddir: &PIDDIR /some/dir/httpd.pid

ojob:
  daemon: true
  unique: 
    pidFile     : *PIDDIR
    killPrevious: false

include:
  - oJobHTTPd.yaml

todo:
  - name: HTTP Start Server
    args:
      port: *PORT

  - name: Prepare my file browser
  - name: Prepare default
  #- name: Prepare my docs

###########################################################
# The code

jobs:
  # Serves any file available in /data (canonical path)
  - name: Prepare default
    to  : HTTP Service
    args: 
      uri       : /
      port      : *PORT
      execURI   : "return ow.server.httpd.replyFile(server, '/data', '/', request.uri);"

  # Provides a file browser
  - name: Prepare my file browser
    to  : HTTP File Browse
    args: 
      uri       : /browse
      port      : *PORT
      path      : /data

  ## What to answer to requests to /docs
  #- name: Prepare my docs
  #  to  : HTTP Service
  #  args: 
  #    uri       : /docs
  #    port      : *PORT
  #    execURI   : "return ow.server.httpd.replyFileMD(server, '/data/docs', '/docs', request.uri);"